when:
  event: [push, pull_request]
  branch: main

matrix:
  PYTHON_VERSION:
    - "3.12"
    - "3.13"
    - "3.14"

steps:
  lint:
    image: ghcr.io/astral-sh/uv:python3.14-bookworm-slim
    commands:
      - uv sync --no-python-downloads
      - uv run task lint
      - uv run task mypy

  test:
    image: ghcr.io/astral-sh/uv:python${PYTHON_VERSION}-bookworm-slim
    commands:
      - uv sync --no-python-downloads
      - uv run task test
