when:
  event: [push, pull_request]
  branch: main

steps:
  lint:
    image: python:latest
    commands:
      - pip install uv
      - uv sync --locked --frozen --no-editable --no-python-downloads --python python3
      - uv run task lint --no-python-downloads --python python3
      - uv run task mypy --no-python-downloads --python python3
